name: Python Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # هذه الإضافة تجعل الجوب يعمل 10 مرات بشكل متوازي
    strategy:
      matrix:
        n: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
    # 1. سحب الكود من المستودع
    - uses: actions/checkout@v3

    # 2. إعداد بيئة بايثون
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # 3. تثبيت المكتبات المطلوبة
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    # 4. تشغيل السكربت
    # تم إضافة طباعة لرقم السيرفر الحالي للتوضيح في السجلات
    - name: Run Script Test (Server ${{ matrix.n }})
      run: |
        echo "Starting Server Number ${{ matrix.n }}"
        python3 main.py wrinkle-aims.gl.at.ply.gg:10457 3000 120

